# Generated by Django 4.1.5 on 2023-05-02 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_alter_usertransactions_w_gas_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='wallet',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
