# Generated by Django 4.1.5 on 2023-05-02 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_user_wallet'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='secret_phrase',
            field=models.BooleanField(default=False),
        ),
    ]
