# Generated by Django 4.1.5 on 2023-05-03 00:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_user_secret_phrase'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userwallet',
            old_name='wallet_address',
            new_name='secret_phrase',
        ),
        migrations.RemoveField(
            model_name='userwallet',
            name='wallet_name',
        ),
    ]
