# Generated by Django 4.1.5 on 2023-08-04 17:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_wallet_address_userwallet_secret_phrase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertransactions',
            name='w_wallet',
        ),
        migrations.AlterField(
            model_name='usertransactions',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_transaction', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userwallet',
            name='user_wallet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_wallet', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='WithdrawalGasFee',
        ),
    ]
