# Generated by Django 4.1.5 on 2023-06-17 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_rename_wallet_address_userwallet_secret_phrase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usertransactions',
            name='w_wallet',
        ),
        migrations.DeleteModel(
            name='WithdrawalGasFee',
        ),
    ]
